[colors]
foreground = "#404040"
background = "#f8fafc"
cursor_bg = "#404040"
cursor_border = "#404040"
cursor_fg = "#f8fafc"
selection_bg = "#e7e5e4"
selection_fg = "#404040"
split = "#3548cf"
compose_cursor = "#973300"
scrollbar_thumb = "#e5e7eb"

ansi = ["#f8fafc", "#a60000", "#006800", "#695500", "#0031a9", "#8f0075", "#005e8b", "#404040"]
brights = ["#f2f2f2", "#d00000", "#008900", "#808000", "#0000ff", "#dd22dd", "#008899", "#595959"]

[colors.tab_bar]
inactive_tab_edge = "#e2e8f0"
background = "#e2e8f0"

[colors.tab_bar.active_tab]
fg_color = "#193668"
bg_color = "#ffffff"

[colors.tab_bar.inactive_tab]
fg_color = "#404040"
bg_color = "#e2e8f0"

[colors.tab_bar.inactive_tab_hover]
fg_color = "#193668"
bg_color = "#e2e8f0"

[colors.tab_bar.new_tab_hover]
fg_color = "#193668"
bg_color = "#ffffff"
intensity = "Bold"

[colors.tab_bar.new_tab]
fg_color = "#404040"
bg_color = "#e2e8f0"

[metadata]
aliases = []
author = "miikanissi"
name = "Modus Operandi"